package GP.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import GP.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.04.26 11:20:21 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KilpailuTest {



  // Generated by ComTest BEGIN
  /** testGetNimi42 */
  @Test
  public void testGetNimi42() {    // Kilpailu: 42
    Kilpailu usa = new Kilpailu(); 
    usa.vastaaSkateAmerica(); 
    { String _l_=usa.getNimi(),_r_="Skate America"; if ( !_l_.matches(_r_) ) fail("From: Kilpailu line: 45" + " does not match: ["+ _l_ + "] != [" + _r_ + "]");}; 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testLuo89 */
  @Test
  public void testLuo89() {    // Kilpailu: 89
    Kilpailu usa1 = new Kilpailu(); 
    assertEquals("From: Kilpailu line: 91", 0, usa1.getIdNro()); 
    usa1.luo(); 
    Kilpailu usa2 = new Kilpailu(); 
    usa2.luo(); 
    int n1 = usa1.getIdNro(); 
    int n2 = usa2.getIdNro(); 
    assertEquals("From: Kilpailu line: 97", n2-1, n1); 
  } // Generated by ComTest END
}