package GP.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import GP.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.04.26 11:22:21 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class LuistelijaTest {


  // Generated by ComTest BEGIN
  /** testLuo143 */
  @Test
  public void testLuo143() {    // Luistelija: 143
    Luistelija alexTrus = new Luistelija(); 
    assertEquals("From: Luistelija line: 145", 0, alexTrus.getLuistelijaId()); 
    alexTrus.luo(); 
    Luistelija anya = new Luistelija(); 
    anya.luo(); 
    int n1 = alexTrus.getLuistelijaId(); 
    int n2 = anya.getLuistelijaId(); 
    assertEquals("From: Luistelija line: 151", n2-1, n1); 
  } // Generated by ComTest END
}